repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.3
    hooks:
    - id: trailing-whitespace
    - id: autopep8-wrapper
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: flake8
      args: [--max-line-length=180]
    - id: requirements-txt-fixer
-  repo: git://github.com/pre-commit/mirrors-yapf
   sha: v0.17.0
   hooks:
    - id: yapf
-  repo: git://github.com/asottile/reorder_python_imports
   sha: v0.3.5
   hooks:
   - id: reorder-python-imports
